# Generated by Django 5.1.1 on 2024-11-12 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_head', models.CharField(default='hustlr', max_length=60)),
                ('banner_name', models.CharField(max_length=50)),
                ('banner_image', models.ImageField(default='b', upload_to='statics/images')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='b', upload_to='statics/images')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glass_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='google',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='i', upload_to='statics/images')),
            ],
        ),
        migrations.CreateModel(
            name='shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='a', upload_to='statics/images')),
                ('shape_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='i', upload_to='statics/images')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.CharField(default='z', max_length=100)),
                ('image', models.ImageField(default='c', upload_to='statics/images')),
                ('title', models.CharField(default='d', max_length=100)),
                ('description', models.CharField(default='d', max_length=100)),
                ('rating', models.CharField(default='d', max_length=50)),
                ('offer', models.CharField(default='d', max_length=100)),
                ('image2', models.ImageField(default='d', upload_to='statics/images')),
                ('image3', models.ImageField(default='d', upload_to='statics/images')),
                ('image4', models.ImageField(default='d', upload_to='statics/images')),
                ('image5', models.ImageField(default='d', upload_to='statics/images')),
                ('image6', models.ImageField(default='d', upload_to='statics/images')),
                ('image7', models.ImageField(default='d', upload_to='statics/images')),
                ('image8', models.ImageField(default='d', upload_to='statics/images')),
                ('image9', models.ImageField(default='d', upload_to='statics/images')),
                ('image10', models.ImageField(default='d', upload_to='statics/images')),
                ('image11', models.ImageField(default='d', upload_to='statics/images')),
                ('name', models.CharField(default='d', max_length=100)),
                ('pro_d', models.CharField(default='d', max_length=200)),
                ('description1', models.CharField(default='d', max_length=100)),
                ('rating1', models.CharField(default='d', max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('offer2', models.CharField(default='d', max_length=200)),
                ('caption', models.CharField(default='d', max_length=200)),
                ('airess1', models.ImageField(default='e', upload_to='statics/images')),
                ('airess2', models.ImageField(default='e', upload_to='statics/images')),
                ('airess3', models.ImageField(default='e', upload_to='statics/images')),
                ('airess4', models.ImageField(default='e', upload_to='statics/images')),
                ('airess5', models.ImageField(default='e', upload_to='statics/images')),
                ('airess6', models.ImageField(default='e', upload_to='statics/images')),
                ('airess7', models.ImageField(default='e', upload_to='statics/images')),
                ('airess8', models.ImageField(default='e', upload_to='statics/images')),
                ('airess9', models.ImageField(default='e', upload_to='statics/images')),
                ('airess10', models.ImageField(default='e', upload_to='statics/images')),
                ('banner_name', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='banner_name1', to='app.banner')),
                ('category_name', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='categoy_name', to='app.category')),
                ('glass_name', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='glass_name2', to='app.glass')),
                ('shape_name', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='shape_name1', to='app.shape')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pro_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_d1', to='app.products')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pro_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_d2', to='app.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
