# Generated by Django 5.1.1 on 2024-11-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='contactus',
            name='l_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
