# Generated by Django 5.0.3 on 2024-08-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_google'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Quantity',
        ),
    ]
