# Generated by Django 5.1.1 on 2024-11-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_contactus_f_name_contactus_l_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='f_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='l_name',
            new_name='lname',
        ),
    ]
