# Generated by Django 5.1.1 on 2024-11-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_f_name_contactus_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
