# Generated by Django 5.1.3 on 2024-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_contactus_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='sign',
            name='first_name',
            field=models.CharField(default='fname', max_length=50),
        ),
        migrations.AddField(
            model_name='sign',
            name='last_name',
            field=models.CharField(default='lasname', max_length=40),
        ),
    ]
