# Generated by Django 5.1.3 on 2024-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_sign_username_sign_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_image', models.ImageField(default='frameImage', upload_to='statics/images')),
                ('frame_name', models.CharField(default='square', max_length=50)),
            ],
        ),
    ]
