# Generated by Django 5.1.3 on 2024-12-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='banners_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
