# Generated by Django 5.1.3 on 2024-12-06 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='frame_size',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='size2', to='app.size'),
        ),
    ]
