# Generated by Django 5.1.3 on 2024-12-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_brands_color_alter_size_frame_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='brand2', to='app.brands'),
        ),
        migrations.AddField(
            model_name='products',
            name='frame_color',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='app.color'),
        ),
    ]
