# Generated by Django 5.1.3 on 2024-12-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_products_brand_products_frame_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='airess10',
        ),
        migrations.RemoveField(
            model_name='products',
            name='airess9',
        ),
        migrations.RemoveField(
            model_name='products',
            name='offer2',
        ),
    ]
