# Generated by Django 5.1.3 on 2024-12-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_products_slider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='frame_name',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, related_name='frame2', to='app.frame'),
        ),
    ]
