# Generated by Django 5.1.3 on 2024-12-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_products_frame_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rating1',
        ),
    ]
